version: 1
disable_existing_loggers: False

formatters:
  table:
    style: "{"
    format: "{asctime} │ {levelname:<8} │ {message}"
  simple:
    format: "%(message)s"
  colored:
    format: "\e[38;5;45m%(asctime)s \e[38;5;226m%(levelname)s\e[0m\n%(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  file: &file
    class: logging.handlers.RotatingFileHandler
    level: INFO
    filename: server.log
    formatter: simple
    maxBytes: 10485760
    backupCount: 3
    encoding: utf8
  access:
    <<: *file
    filename: access.log
    formatter: table

loggers:
  api:
    level: DEBUG
    handlers: [console, file]
    propagate: False
  tornado.access:
    level: INFO
    handlers: [console, access]
    propagate: False
  tornado.application:
    level: INFO
    handlers: [console, file]
    propagate: False

root:
  level: INFO
  handlers: [console]
